import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import mongoose from "mongoose";
import cookieParser from "cookie-parser";

import orderRouter from "./routes/order";
import productRouter from "./routes/product";
import authRouter from "./routes/auth";
import categoryRouter from "./routes/category";
import uploadRouter from "./routes/upload";
import heroRouter from "./routes/hero";
import userRouter from "./routes/user";
import typesRouter from "./routes/type";

dotenv.config();
const app = express();
app.use(express.json());
app.use(cors({ origin: true, credentials: true }));
app.use(cookieParser());
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));
mongoose.connect(process.env.DB_URL);
app.use("/api", productRouter);
app.use("/api", authRouter);
app.use("/api", categoryRouter);
app.use("/api", uploadRouter);
app.use("/api", heroRouter);
app.use("/api", userRouter);
app.use("/api", typesRouter);
app.use("/api", orderRouter);
export const viteNodeApp = app;
